Update django.po
MicrobitPolska/microbitpolskaorg pull request #13
Opened 2016-11-24 19:09 UTC by PowerMarcus

Polish translate

2016-11-24 20:04 UTC, barrachri commented
Hi Marek, thanks for the amazing job.
I am going to check and merge this in the next days.

2016-11-30 00:29 UTC, karolinabaran requested changes
Hej Marek, możesz tylko jeszcze poprawić twoje piękne tłumaczenie w kilku miejscach, w których zrobiłam mały review :) Pozdro!

2016-11-30 00:29 UTC, karolinabaran commented on locale/pl/LC_MESSAGES/django.po
> +"dla młodzierzy. Przy okazji zabawy uczysz się programowania w języku używanym niemalże "
dla młodzie**ż**y
(bo się jeszcze źle nauczą;)

2016-11-30 00:29 UTC, karolinabaran commented on locale/pl/LC_MESSAGES/django.po
> +"                    <p>W Wielkiej Brytanii podarowało <b><a href=\"http://www.bbc.co."
W Wielkiej Brytanii podarowa**n**o
(chyba tak miało być?)

2016-11-30 00:29 UTC, karolinabaran commented on locale/pl/LC_MESSAGES/django.po
> +"\"http://berlincodeofconduct.org/\"><b>Berlińskim Kodem Postępowania</b></a>.</p>\n"
chyba u nas mówi się Kodeksem bardziej niż Kodem :)

2016-11-30 00:29 UTC, karolinabaran commented on locale/pl/LC_MESSAGES/django.po
> +"                    <p>Wszelkie pytania związane z Kodem Postępowania skieruj do organizatorów  "
j.w.

2016-11-30 03:14 UTC, PowerMarcus commented
minor adjustments

2016-11-30 10:13 UTC, merged